#!/usr/bin/bash
#

if [ $# -eq 0 ]
then
	echo "Usage: vid <dir1> <dir2> <file(s)>"
	exit 0
fi

DIR1=$1
DIR2=$2
shift 2


for i in $*
do
	FILE1=$DIR1/$i
	FILE2=$DIR2/$i

	if ! cmp -s $FILE1 $FILE2
	then
		gvim -d $FILE1 $FILE2
		wait
	fi
done
